base_url = "https://lifjellopp.no/"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
subtitle = "Midt-Telemarks tøffeste klatreritt"

menu_items = [
  { name = "Registrering", path = "/registrering" },
  { name = "Praktisk", path = "/praktisk" },
  { name = "Trase", path = "/trase" },
#  { name = "Galleri", path = "/galleri" },
  { name = "Resultater", path = "/resultater" },
]
